# A seção principal, onde todos os contêineres (serviços) são definidos
services:
  # Serviço da API
  api:
    build:
      context: .  # Diretório de contexto de build
      target: development  # Alvo de build definido no Dockerfile
    container_name: api-portal-ong-ser-amor  # Nome do contêiner
    restart: unless-stopped  # Política de reinício do contêiner
    env_file:
      - .env  # Arquivo de variáveis de ambiente
    ports:
      - "${API_PORT}:${API_PORT}"  # Mapeamento da porta da API
    depends_on:
      - db  # Dependência do serviço de banco de dados
    volumes:
      - .:/usr/src/app  # montagem do diretório local -> dentro do contêiner
      - /usr/src/app/node_modules  # Evita que o node_modules do host sobrescreva o do contêiner

  # Serviço do Banco de Dados
  db:
    image: postgres:17  # Imagem oficial do PostgreSQL
    container_name: db-portal-ong-ser-amor  # Nome do contêiner
    restart: unless-stopped  # Política de reinício do contêiner
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"  # Mapeamento da porta padrão do PostgreSQL
    volumes:
      - db_data:/var/lib/postgresql/data  # Volume para persistência dos dados

# Definição de volumes para persistência de dados
volumes:
  db_data:
    driver: local
