export enum StatusFormacao {
  COMPLETO = 'COMPLETO',
  CURSANDO = 'CURSANDO',
  INCOMPLETO = 'INCOMPLETO',
}

export enum TipoVoluntario {
  COORDENADOR_CURSOS = 'COORDENADOR_CURSOS',
  PROFESSOR = 'PROFESSOR',
}
