export enum EstadoCivil {
  CASADO = 'CASADO',
  DIVORCIADO = 'DIVORCIADO',
  SOLTEIRO = 'SOLTEIRO',
  UNIAO_ESTAVEL = 'UNIAO_ESTAVEL',
  VIUVO = 'VIUVO',
}

export enum NivelEscolaridade {
  ENSINO_FUNDAMENTAL_INCOMPLETO = 'ENSINO_FUNDAMENTAL_INCOMPLETO',
  ENSINO_FUNDAMENTAL_COMPLETO = 'ENSINO_FUNDAMENTAL_COMPLETO',
  ENSINO_MEDIO_INCOMPLETO = 'ENSINO_MEDIO_INCOMPLETO',
  ENSINO_MEDIO_COMPLETO = 'ENSINO_MEDIO_COMPLETO',
  ENSINO_SUPERIOR_INCOMPLETO = 'ENSINO_SUPERIOR_INCOMPLETO',
  ENSINO_SUPERIOR_COMPLETO = 'ENSINO_SUPERIOR_COMPLETO',
  SEM_ESCOLARIDADE = 'SEM_ESCOLARIDADE',
}

export enum VinculoEmpregaticio {
  APOSENTADO = 'APOSENTADO',
  AUTONOMO = 'AUTONOMO',
  DESEMPREGADO = 'DESEMPREGADO',
  EMPREGADO_CLT = 'EMPREGADO_CLT',
  INFORMAL = 'INFORMAL',
  OUTRO = 'OUTRO',
}
